(include_subdirs unqualified)

(env (dev (flags (:standard -warn-error -26))))
(library
 (name collaborative_editor)
 (preprocess (pps ppx_deriving.show ppx_bin_prot))
 (libraries eio_main )
(modules terminal types term_driver configurer_intf buffer configure window frame textholder renderer widget )
)
